### ISSUE TITLE
Hedera Sourcify search views have different behavior

### ISSUE THREAD

**Issue by ed-marquez** [hashgraph/hedera-sourcify#91]
### Description

The search tool from the following link does not work as expected: 
https://repository-verify.hashscan.io/select-contract/ 

See repro steps below for details.

### Steps to reproduce

- Contract address: 0x00000000000000000000000000000000002e7a5d
- HashScan View (Partial Match ✅): https://hashscan.io/mainnet/contract/0.0.3045981

- Search result from this view: https://verify.hashscan.io/#/lookup
<img width="1339" alt="image" src="https://github.com/hashgraph/hedera-sourcify/assets/72571340/ae256057-756d-49f0-81eb-bd7b07b2b444">

- Search result from this view: https://repository-verify.hashscan.io/select-contract/
<img width="896" alt="image" src="https://github.com/hashgraph/hedera-sourcify/assets/72571340/f9bff0ba-45b8-43e7-8612-2ad6a49cdf2b">

For clarity, the verification results exist in Hedera Sourcify: https://repository-verify.hashscan.io/contracts/partial_match/295/0x00000000000000000000000000000000002E7A5D/

**The search functionality from one of the views is what is broken.**

### Hedera network

mainnet, testnet

### Version

Latest

### Operating system

macOS

**Comment by Reccetech** [comment]
This lookup page doesn't work and should be deprecated: 
https://repository-verify.hashscan.io/select-contract/

All lookups should route to: 
https://verify.hashscan.io/#/lookup

**Comment by svienot** [comment]
The issue is:
 - the _lookup_ page (https://verify.hashscan.io/#/lookup) support both plain address and mixed-case checksum address (per ERC-55). If you enter `0x00000000000000000000000000000000002e7a5d` it converts it into `0x00000000000000000000000000000000002E7A5D`
 - the _select-contract_ form (https://repository-verify.hashscan.io/select-contract/) actually works but only supports the mixed-case checksum address, i.e. `0x00000000000000000000000000000000002E7A5D`
Hence the disconnect.

This code is a dependency (furthermore an indirect one) of hedera-sourcify, and code that we currently do not control, so we need to investigate what is the best way to mitigate.
