### ISSUE TITLE
Enable `create2` server tests

### ISSUE THREAD

**Issue by acuarica** [hashgraph/hedera-sourcify#97]
The endpoints missing are

- `/session/verify/create2`
- `/session/verify/create2/compile`
- `/verify/create2`

**Comment by Nana-EC** [comment]
@acuarica do we recall why these endpoints don't work. I believe it had to do with the session key not being used in our case.

**Comment by acuarica** [comment]
It is because a config flag, `create2`, needs to be set to make them available.

**Comment by svienot** [comment]
So this is a configurability we have added. We decided to (at least) hide the Create2 verification because it was not clear how useful it was in our context... So the feature is currently not enabled in the UI, and the corresponding end-points are also not exposed.
When we forked, the Create2 verification was supposed to imply that the client provide a TOKEN, in order to avoid spamming. The server was configured for all supported tokens via the .env file.
I saw recently that in today's sourcify.dev the functionality has evolved such that this TOKEN business is gone and the user seems to have to login to be able to use this feature...
